---
- name: Auto Outage GML Observabilidade
  hosts: localhost
  gather_facts: false
  vars:
    dynatrace_validate_only: true

  roles:
    # Descobre as GMUDs, ativos afetados e janela de manutenção no Jira.
    - role: descoberta

    # Localiza os ativos no Dynatrace e cria a Maintenance Window.
    - role: outage
